[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "gql>=3.5.2",
    "requests-toolbelt>=1.0.0",
    "streamlit>=1.43.2",
]
